- name: Install epel-release
  ansible.builtin.yum:
    name: "epel-release"
    update_cache: yes
    state: latest
  when: ansible_distribution != "Fedora"

- name: Update all packages to their latest version
  ansible.builtin.yum:
    name: "*"
    update_cache: yes
    state: latest

- name: Install ansible
  ansible.builtin.yum:
    name: "{{ package_list_to_install }}"
    update_cache: yes
    state: latest

- name: Remove ansible
  ansible.builtin.yum:
    name: "{{ package_list_to_remove }}"
    state: absent