---
- name: Task and Roles that run by ansible-pull
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Import ansile roles to run by ansible-pull
      ansible.builtin.import_role:
        name: package-manage
