---
- name: Install ansible and automate server setup using ansible-pull
  hosts: all
  become: true
  vars:
    pull_url: "https://github.com/masoud-maghsoudi/ansible-pull-automate-server-setup.git" # Repository URL to fetch and run ansible playbooks.
  tasks:
    - name: Run ansible roles
      ansible.builtin.import_role:
        name: ansible-init

    - name: Schedule ansible-pull from repository
      ansible.builtin.cron:
        name: "ansible-pull schedule"
        special_time: daily
        user: root
        job: "ansible-pull --url ${{ pull_url }}"
        backup: true
